#-------------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC with ManagedNodes
#
# eksctl create cluster -f eks-cluster-managednodes.yaml
# eksctl delete cluster -f eks-cluster-managednodes.yaml
# eksctl update cluster -f eks-cluster-managednodes.yaml
#-------------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : k8s-prod
  version: "1.31"
  region : eu-west-1

vpc:
 subnets:
   public:
      eu-west-1a: { id: subnet-xxxxxxxxxxxxxxxxx }
      eu-west-1b: { id: subnet-xxxxxxxxxxxxxxxxx }

   private:
      eu-west-1a: { id: subnet-xxxxxxxxxxxxxxxxx }
      eu-west-1b: { id: subnet-xxxxxxxxxxxxxxxxx }

managedNodeGroups:
  - name             : worker-group-1
    instanceType     : m5.large
    desiredCapacity  : 2
    labels           : { role: worker1 }   
    volumeSize       : 80
    privateNetworking: true
    
  - name             : worker-group-2
    instanceType     : r5.large
    desiredCapacity  : 2
    volumeSize       : 100
    labels           : { role: worker2 }    
    privateNetworking: true
